"""Demo region constants — re-exported from config for modular imports."""

from __future__ import annotations

from src.config import (
    OKANAGAN_AOI_BBOX,
    OKANAGAN_AOI_WKT,
    OKANAGAN_BC_HYDRO_REGION,
    OKANAGAN_CORRIDOR_BUFFER_M,
    OKANAGAN_HISTORY_START_DATE,
    OKANAGAN_MAP_ZOOM,
    OKANAGAN_MUNICIPALITIES,
    OKANAGAN_PILOT_LAT,
    OKANAGAN_PILOT_LON,
    OKANAGAN_REGION_NAME,
    OKANAGAN_SEGMENT_LENGTH_KM,
    SURREY_AOI_BBOX,
    SURREY_AOI_WKT,
    SURREY_BC_HYDRO_REGION,
    SURREY_MAP_ZOOM,
    SURREY_PILOT_LAT,
    SURREY_PILOT_LON,
    SURREY_REGION_NAME,
)

__all__ = (
    "OKANAGAN_AOI_BBOX",
    "OKANAGAN_AOI_WKT",
    "OKANAGAN_BC_HYDRO_REGION",
    "OKANAGAN_CORRIDOR_BUFFER_M",
    "OKANAGAN_HISTORY_START_DATE",
    "OKANAGAN_MAP_ZOOM",
    "OKANAGAN_MUNICIPALITIES",
    "OKANAGAN_PILOT_LAT",
    "OKANAGAN_PILOT_LON",
    "OKANAGAN_REGION_NAME",
    "OKANAGAN_SEGMENT_LENGTH_KM",
    "SURREY_AOI_BBOX",
    "SURREY_AOI_WKT",
    "SURREY_BC_HYDRO_REGION",
    "SURREY_MAP_ZOOM",
    "SURREY_PILOT_LAT",
    "SURREY_PILOT_LON",
    "SURREY_REGION_NAME",
)
